platform :ios, '14.0'

target 'iosApp' do
  use_frameworks! :linkage => :static

  pod 'shared', :path => '../shared'

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Cloudinary'
  pod 'Kingfisher' # Image caching: memory + disk, industry standard for scalable feeds
  pod 'lottie-ios' # Lottie animations for loading screens

end